### PR TITLE
Updated to 1.7.10

### PR DESCRIPTION
**Pull request by Parker8283**
Was waiting on LiteLoader 1.7.10 support from ForgeGradle, and since it was taking a while, I decided to make the PR to the FG repository myself! It was accepted, so I was able to update to 1.7.10 for you. The only real error was in the IC2Power, where get energy value now returns a double instead of an int. Also cleaned up some deprecation warnings.

### CODE REVIEW

**Comment by Parker8283** [comment]
Any news on this @Uristqwerty? It appears that you got a 1.7.2 release out. If/when you pull this, I'd be willing to port to 1.8 for you.

**Comment by Uristqwerty** [comment]
College has left me with far less free time than I expected, and on the occasions when I *have* been playing Minecraft, it's been 1.6.4, which is troublesome, as using the mod has often been the driving force behind me spending time developing it.

As for code, a "recent" (many months ago, now) Railcraft issue revealed to me that the entire CraftType class was subtly wrong. It was supposed to represent an ItemStack, while allowing for use in Collections (keys in HashMaps, any type of SortedSet or SortedMap), but I delayed (and then forgot about) adding NBT support, which caused Railcraft's issue (NBT was used for certain track appearance, so it looked wrong in the item list).

At the same time, it made me realize that the Ore Dictionary handling of it was broken, as the hashcode and sort order was based off the first entry of the Ore's ArrayList, which I realized is mutable, potentially leading to unpredictable results if any mod ever altered the source data during gameplay. I had a partially-completed rework of CraftType when I last touched the code.

On the positive side, the Material Energy^4 pack is for Minecraft 1.7, which will hopefully give me the inspiration to get back into CraftGuide development at some point in the relatively near future.


Sorry about basically disappearing back around September, though.

**Comment by Parker8283** [comment]
All good, man. I know how much school can get in the way. If you'd like, I'll take a look into your issues and see if I can't get a fix.

**Comment by Parker8283** [comment]
Heh, I totally forgot about this! :P

You may want to bump the Forge version, LL revision, BC and ic2 versions, to make sure you have full compat with current 1.7.10

**Pull request merged**
